import * as fs from 'fs';
import * as path from 'path';

function normalizeCookieDomain(targetUrl: string): string {
  try {
    const host = String(new URL(targetUrl).hostname || '').trim().toLowerCase();
    if (!host) return '.localhost';
    if (host === 'youtu.be' || host.endsWith('.youtu.be')) return '.youtube.com';
    return host.startsWith('.') ? host : `.${host}`;
  } catch {
    return '.localhost';
  }
}

function isLikelyNetscapeCookieFile(raw: string): boolean {
  const t = String(raw || '').trim();
  if (!t) return false;
  if (t.startsWith('# Netscape HTTP Cookie File')) return true;
  const lines = t.split(/\r?\n/).map((x) => x.trim()).filter(Boolean);
  return lines.some((line) => !line.startsWith('#') && line.split('\t').length >= 7);
}

function parseCookieHeaderLike(rawCookieHeader: string): Array<{ name: string; value: string }> {
  return String(rawCookieHeader || '')
    .replace(/\r/g, ' ')
    .replace(/\n/g, ' ')
    .trim()
    .split(';')
    .map((part) => String(part || '').trim())
    .filter(Boolean)
    .map((part) => {
      const eq = part.indexOf('=');
      if (eq <= 0) return { name: '', value: '' };
      const name = part
        .slice(0, eq)
        .replace(/[\t\r\n]/g, '')
        .trim();
      const value = part
        .slice(eq + 1)
        .replace(/[\t\r\n]/g, ' ')
        .replace(/[\u0000-\u001f\u007f]/g, '')
        .trim();
      return { name, value };
    })
    .filter((x) => x.name.length > 0);
}

function parseNetscapeCookieFile(rawNetscape: string): Array<{ name: string; value: string }> {
  const out: Array<{ name: string; value: string }> = [];
  const lines = String(rawNetscape || '').split(/\r?\n/);
  for (const lineRaw of lines) {
    const line = String(lineRaw || '').trim();
    if (!line || line.startsWith('#')) continue;
    const cols = lineRaw.split('\t');
    if (cols.length < 7) continue;
    const name = String(cols[5] || '').trim();
    const value = String(cols.slice(6).join('\t') || '')
      .replace(/[\t\r\n]/g, ' ')
      .replace(/[\u0000-\u001f\u007f]/g, '')
      .trim();
    if (!name) continue;
    out.push({ name, value });
  }
  return out;
}

function sanitizeCookiePairs(pairs: Array<{ name: string; value: string }>): Array<{ name: string; value: string }> {
  return pairs.filter((x) => {
    const name = String(x.name || '').trim();
    const value = String(x.value || '').trim();
    if (!name) return false;
    if (!/^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/.test(name)) return false;
    // Drop malformed non-ASCII cookie values that break yt-dlp cookie parser.
    if (/[^\x20-\x7E]/.test(value)) return false;
    return true;
  });
}

function parseCookieHeader(cookieHeader: string): Array<{ name: string; value: string }> {
  const raw = String(cookieHeader || '').trim();
  if (!raw) return [];
  const pairs = isLikelyNetscapeCookieFile(raw)
    ? parseNetscapeCookieFile(raw)
    : parseCookieHeaderLike(raw);
  return sanitizeCookiePairs(pairs);
}

export function createYtDlpCookieFile(params: {
  cookieHeader?: string;
  targetUrl: string;
  outputDir: string;
  filePrefix?: string;
}): string | null {
  const cookieHeader = String(params.cookieHeader || '').trim();
  if (!cookieHeader) return null;

  const cookies = parseCookieHeader(cookieHeader);
  if (cookies.length === 0) return null;

  const domain = normalizeCookieDomain(params.targetUrl);
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by video-creator at runtime for yt-dlp.',
    ...cookies.map(({ name, value }) => `${domain}\tTRUE\t/\tTRUE\t0\t${name}\t${value}`),
    '',
  ];

  const outputDir = path.resolve(String(params.outputDir || '.'));
  fs.mkdirSync(outputDir, { recursive: true });
  const prefix = String(params.filePrefix || 'yt-dlp-cookies').replace(/[^a-zA-Z0-9._-]/g, '-');
  const filePath = path.join(outputDir, `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}.txt`);
  fs.writeFileSync(filePath, lines.join('\n'), 'utf8');
  return filePath;
}

export function safeUnlink(filePath?: string | null): void {
  const target = String(filePath || '').trim();
  if (!target) return;
  try {
    if (fs.existsSync(target)) fs.unlinkSync(target);
  } catch {
    // ignore cleanup errors
  }
}
